Repository theapexlab/ra-data-blitz, pull requests merged in 2022-02, with the labels that each got.

#5 Add pr checks
  .eslintignore
  .eslintrc
  .github/workflows/pr.yml
  .gitignore
  package.json
  yarn-error.log
  yarn.lock
Labels: size/XXL

#4 Add handle root option
  README.md
  src/index.ts
  src/types.ts
  src/utils/getHandler.test.ts
  src/utils/getHandler.ts
  test/setup.ts
Labels: size/M

#7 Release 0.0.10
  README.md
  package.json
  src/index.ts
  src/types.ts
  src/utils/getHandler.test.ts
  src/utils/getHandler.ts
  test/setup.ts
Labels: size/M

#9 Release v0.0.11
  README.md
  package.json
  src/index.ts
  src/utils/getHandler.test.ts
  src/utils/getHandler.ts
Labels: size/M

#10 fix: handlerRoot
  package.json
  src/utils/getHandler.ts
Labels: size/XS
